server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice2
    username: root
    password: Admin@123
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    showSql-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
